# Use a imagem oficial do Node.js
FROM node:18

# Defina o diretório de trabalho
WORKDIR /app

# Copie os arquivos do projeto para o container
COPY . .

# Instale as dependências
RUN npm install

# Exponha a porta que o serviço vai rodar
EXPOSE 3002

# Defina a variável de ambiente
ENV PORT=3002

# Inicie o serviço
CMD ["npm", "run", "start:prod"]
